package org.reduxkotlin.routing.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo

private val REDUX_MODULE = ClassName("org.reduxkotlin.routing", "ReduxModule")
private val ROUTING_BUILDER = ClassName("org.reduxkotlin.routing", "RoutingBuilder")

/** Renders the registrar object and writes it to the generated common sources. */
internal fun writeRegistrar(
    codeGenerator: CodeGenerator,
    moduleName: String,
    generatedPackage: String,
    handlersByModel: Map<String, List<HandlerInfo>>,
    initials: Map<String, InitialInfo>,
    originatingFiles: List<KSFile>,
) {
    val contribute = FunSpec.builder("contribute")
        .addModifiers(KModifier.OVERRIDE)
        .receiver(ROUTING_BUILDER)

    // Collect every top-level function reference (providers + handlers) as MemberNames
    // so we can detect simple-name clashes and emit aliased imports — KotlinPoet's %M
    // does NOT auto-alias clashing simple names from different packages.
    val usedMembers = mutableListOf<MemberName>()

    // Deterministic order: models by FQN, handlers by (action FQN, handler FQN).
    for (modelFqn in handlersByModel.keys.sorted()) {
        val handlers = handlersByModel.getValue(modelFqn)
            .sortedWith(compareBy({ it.actionFqn }, { it.handlerFqn }))
        val initial = initials.getValue(modelFqn)
        val modelClass = handlers.first().modelDecl.toClassName()
        val provider = MemberName(initial.providerPackage, initial.providerSimpleName)
        usedMembers += provider
        contribute.beginControlFlow("model<%T>(%M())", modelClass, provider)
        for (h in handlers) {
            val action = h.actionDecl.toClassName()
            val handler = MemberName(h.handlerPackage, h.handlerSimpleName)
            usedMembers += handler
            contribute.addStatement("on<%T> { s, a -> %M(s, a) }", action, handler)
        }
        contribute.endControlFlow()
    }

    val registrar = TypeSpec.objectBuilder(moduleName)
        .addKdoc(
            "Generated by redux-kotlin-routing-codegen from @Reduce handlers.\n" +
                "Install with `install(%L)`. Configure the name via the `routing.moduleName` KSP arg.",
            moduleName,
        )
        .addSuperinterface(REDUX_MODULE)
        .addFunction(contribute.build())
        .build()

    val fileBuilder = FileSpec.builder(generatedPackage, moduleName).addType(registrar)

    // Alias top-level function imports whose simple names collide across packages.
    usedMembers.distinct().groupBy { it.simpleName }.forEach { (simple, members) ->
        if (members.size > 1) {
            members.sortedBy { it.packageName }.forEachIndexed { index, member ->
                fileBuilder.addAliasedImport(member, "${simple}_$index")
            }
        }
    }

    fileBuilder.build()
        .writeTo(codeGenerator, Dependencies(aggregating = true, *originatingFiles.toTypedArray()))
}
