name: PR

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ktlint
        uses: "vroy/gha-kotlin-linter@v1"
  test:
    needs: ktlint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ./gradlew allTest

      - name: Archive redux-kotlin Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: redux-kotlin_test_reports
          path: redux-kotlin/build/reports/tests

      - name: Archive redux-kotlin-threadsafe Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: redux-kotlin-threadsafe_test_reports
          path: redux-kotlin-threadsafe/build/reports/tests
