name: Resolve Version

on:
  workflow_call:
    inputs:
      desired-version:
        type: string
        description: Optional desired version
        required: false
    outputs:
      version:
        value: ${{ jobs.resolve.outputs.version }}
      snapshot:
        value: ${{ jobs.resolve.outputs.version }}

concurrency:
  cancel-in-progress: true
  group: version-${{ github.workflow }}-${{ github.head_ref || github.ref }}

jobs:
  resolve:
    name: Resolve Version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.desired-version }}
    outputs:
      version: ${{ steps.resolve.outputs.version }}
      snapshot: ${{ steps.resolve.outputs.snapshot }}
    steps:
      - uses: actions/checkout@v3
      - name: Resolve
        id: resolve
        run: |
          project_version=$(cat gradle.properties | grep -Po '^version=\K(.+)')
          version=${VERSION:=$project_version}
          VERSION=${VERSION/v}
          echo "PROJECT_VERSION=${project_version}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"
          if [[ "$VERSION" != "$project_version" ]]; then
            echo "DIFF_VERSION=1" >> $GITHUB_ENV
          fi
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "::set-output name=snapshot::true"
          else
            echo "::set-output name=snapshot::false"
          fi
      - name: Report
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "steps.resolve.outputs.version=${{ steps.resolve.outputs.version }}"
      - name: Create Snapshot
        if: env.DIFF_VERSION == '1'
        run: |
          main_version=$(echo $VERSION | grep -Po '^([0-9]+.){2}(?=.*)')
          patch_version=$(echo $VERSION | grep -Po "^$main_version\\K([0-9]+)(?=.*)")
          patch_version=$(expr $patch_version + 1)
          SNAPSHOT_VERSION="${main_version}${patch_version}-SNAPSHOT"
          echo "SNAPSHOT_VERSION=$SNAPSHOT_VERSION" >> $GITHUB_ENV
          sed -Ei "s|^(version=).*\$|\\1$SNAPSHOT_VERSION|" gradle.properties
      - name: Commit and push SNAPSHOT
        if: env.DIFF_VERSION == '1' && env.PROJECT_VERSION != env.SNAPSHOT_VERSION
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GH_TOKEN || github.token }}
          commit_message: '[ci skip] New SNAPSHOT - ${{ env.SNAPSHOT_VERSION }}'
          target_branch: master
